name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: waproduction-loopademy-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: bash
        run: |
          curl -L --output installer.exe 'https://wamanager-dist.nyc3.cdn.digitaloceanspaces.com/Loopademy%20Setup%201.7.5.exe'
          
      - name: uncompress 
        shell: cmd
        run: |
          7z.exe x installer.exe &&^
          cd $PLUGINSDIR &&^
          7z.exe x app-64.7z -o"C:\installation"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "C:/installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "C:/installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
